title: "AuSIS"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
url: "https://AusisEdu.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  ausis:
    name: AuSIS
    display_name: AuSIS
    avatar: 'assets/images/sal.png'
    email: ausis@anu.edu.au
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/ausisedu
    description: "The Australian Seismometers in Schools Network"

# Social
social:
  instagram: https://www.instagram.com/ausisedu
  facebook: https://www.facebook.com/ausisnetwork/
  twitter: https://twitter.com/ausisedu

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
